/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <assert.h>

//for native audio
#include <SLES/OpenSLES.h>
#include <SLES/OpenSLES_Android.h>

//for native asset manager
#include <sys/types.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>

/* Header for class zhaojing_com_myowntest_activity_NativeAudioActivity */

#ifndef _Included_zhaojing_com_myowntest_activity_NativeAudioActivity
#define _Included_zhaojing_com_myowntest_activity_NativeAudioActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_ABOVE_CLIENT
#define zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_ABOVE_CLIENT 8L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_ADJUST_WITH_ACTIVITY
#define zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_ALLOW_OOM_MANAGEMENT
#define zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_AUTO_CREATE
#define zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_AUTO_CREATE 1L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_DEBUG_UNBIND
#define zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_DEBUG_UNBIND 2L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_EXTERNAL_SERVICE
#define zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_EXTERNAL_SERVICE -2147483648L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_IMPORTANT
#define zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_IMPORTANT 64L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_NOT_FOREGROUND
#define zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_NOT_FOREGROUND 4L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_WAIVE_PRIORITY
#define zhaojing_com_myowntest_activity_NativeAudioActivity_BIND_WAIVE_PRIORITY 32L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_CONTEXT_IGNORE_SECURITY
#define zhaojing_com_myowntest_activity_NativeAudioActivity_CONTEXT_IGNORE_SECURITY 2L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_CONTEXT_INCLUDE_CODE
#define zhaojing_com_myowntest_activity_NativeAudioActivity_CONTEXT_INCLUDE_CODE 1L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_CONTEXT_RESTRICTED
#define zhaojing_com_myowntest_activity_NativeAudioActivity_CONTEXT_RESTRICTED 4L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_APPEND
#define zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_APPEND 32768L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_MULTI_PROCESS
#define zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_MULTI_PROCESS 4L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_NO_LOCALIZED_COLLATORS
#define zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_NO_LOCALIZED_COLLATORS 16L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_PRIVATE
#define zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_PRIVATE 0L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_WORLD_READABLE
#define zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_WORLD_READABLE 1L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_WORLD_WRITEABLE
#define zhaojing_com_myowntest_activity_NativeAudioActivity_MODE_WORLD_WRITEABLE 2L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_RECEIVER_VISIBLE_TO_INSTANT_APPS
#define zhaojing_com_myowntest_activity_NativeAudioActivity_RECEIVER_VISIBLE_TO_INSTANT_APPS 1L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_DEFAULT_KEYS_DIALER
#define zhaojing_com_myowntest_activity_NativeAudioActivity_DEFAULT_KEYS_DIALER 1L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_DEFAULT_KEYS_DISABLE
#define zhaojing_com_myowntest_activity_NativeAudioActivity_DEFAULT_KEYS_DISABLE 0L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define zhaojing_com_myowntest_activity_NativeAudioActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define zhaojing_com_myowntest_activity_NativeAudioActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_DEFAULT_KEYS_SHORTCUT
#define zhaojing_com_myowntest_activity_NativeAudioActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_RESULT_CANCELED
#define zhaojing_com_myowntest_activity_NativeAudioActivity_RESULT_CANCELED 0L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_RESULT_FIRST_USER
#define zhaojing_com_myowntest_activity_NativeAudioActivity_RESULT_FIRST_USER 1L
#undef zhaojing_com_myowntest_activity_NativeAudioActivity_RESULT_OK
#define zhaojing_com_myowntest_activity_NativeAudioActivity_RESULT_OK -1L

//engine interfaces
static SLObjectItf engineObject=NULL;
static SLEngineItf engineEngine;

// output mix interfaces
static SLObjectItf outputMixObject = NULL;
static SLEnvironmentalReverbItf  outputMixEnvironmentalReverb = NULL;

//file descriptor player interface
static SLObjectItf fdPlayerObject=NULL;
static SLPlayItf fdPlayerPlay;
static SLSeekItf fdPlayerSeek;
static SLMuteSoloItf fdPlayerMuteSolo;// slient
static SLVolumeItf fdPlayerVolume;//volume


// aux effect on the output mix, used by the buffer queue player
static const SLEnvironmentalReverbSettings reverbSettings =
        SL_I3DL2_ENVIRONMENT_PRESET_STONECORRIDOR;


/*
 * Class:     zhaojing_com_myowntest_activity_NativeAudioActivity
 * Method:    createEngine
 * Signature: ()V
 */

//create the engine and output mix objects
JNIEXPORT void JNICALL Java_zhaojing_com_myowntest_activity_NativeAudioActivity_createEngine
  (JNIEnv *env, jclass jclazz){

    SLresult result;
    //create engine
    result=slCreateEngine(&engineObject,0,NULL,0,NULL,NULL);
    assert(SL_RESULT_SUCCESS == result);
    (void)result;
    //realize the engine
    result = (*engineObject)->Realize(engineObject,SL_BOOLEAN_FALSE);
    assert(SL_RESULT_SUCCESS ==result);
    (void)result;

    //get the engine interface,which is needed in order to create other objects
    result=(*engineObject)->GetInterface(engineObject,SL_IID_ENGINE,&engineEngine);
    assert(SL_RESULT_SUCCESS==result);
    (void)result;

    //create output mix,with environmental reverb specified as a non-required interface
    const SLInterfaceID ids[1]={SL_IID_ENVIRONMENTALREVERB};
    const SLboolean req[1]={SL_BOOLEAN_FALSE};
    result = (*engineEngine)->CreateOutputMix(engineEngine,&outputMixObject,1,ids,req);
    assert(SL_RESULT_SUCCESS == result);
    (void)result;

    //realize the output mix
    result=(*outputMixObject)->Realize(outputMixObject,SL_BOOLEAN_FALSE);
    assert(SL_RESULT_SUCCESS == result);
    (void)result;

    //get the environmental reverb interface
    result = (*outputMixObject)->GetInterface(outputMixObject,
    SL_IID_ENVIRONMENTALREVERB,&outputMixEnvironmentalReverb);
    if(SL_RESULT_SUCCESS==result){
        result = (*outputMixEnvironmentalReverb)->SetEnvironmentalReverbProperties(
                outputMixEnvironmentalReverb,&reverbSettings);
        (void)result;

    }



}

/*
 * Class:     zhaojing_com_myowntest_activity_NativeAudioActivity
 * Method:    createBufferQueueAudioPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zhaojing_com_myowntest_activity_NativeAudioActivity_createBufferQueueAudioPlayer
  (JNIEnv *env, jclass jclazz);

/*
 * Class:     zhaojing_com_myowntest_activity_NativeAudioActivity
 * Method:    createAssetAudioPlayer
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_zhaojing_com_myowntest_activity_NativeAudioActivity_createAssetAudioPlayer
  (JNIEnv *env, jclass jclazz, jobject assetManager, jstring filename){

    SLresult result;
    //convert java string to utf-8
    const char *utf8=(*env)->GetStringUTFChars(env,filename,NULL);

    assert(NULL!=utf8);
    //use asset manager to open asset by filename
    AAssetManager* mgr=AAssetManager_fromJava(env,assetManager);
    assert(NULL!=mgr);
    AAsset* asset = AAssetManager_open(mgr,utf8,AASSET_MODE_UNKNOWN);

    //release the java string and UTF-8
    (*env)->ReleaseStringUTFChars(env,filename,utf8);

    //the asset might not be found
    if(NULL ==asset){

        return JNI_FALSE;
    }

    //open asset as file descriptor
    off_t start,length;
    int fd = AAsset_openFileDescriptor(asset,&start,&length);
    assert(0<fd);
    AAsset_close(asset);

    //configure audio source
    SLDataLocator_AndroidFD loc_fd={SL_DATALOCATOR_ANDROIDFD,fd,start,length};
    SLDataFormat_MIME format_mime={SL_DATAFORMAT_MIME,NULL,SL_CONTAINERTYPE_UNSPECIFIED};
    SLDataSource audioSrc = {&loc_fd,&format_mime};

    //configure audio sink
    SLDataLocator_OutputMix loc_outmix ={SL_DATALOCATOR_OUTPUTMIX,outputMixObject};
    SLDataSink audioSNK={&loc_outmix,NULL};

    //create audio player
    const SLInterfaceID ids[3]={SL_IID_SEEK,SL_IID_MUTESOLO,SL_IID_VOLUME};
    const SLboolean req[3]={SL_BOOLEAN_TRUE,SL_BOOLEAN_TRUE,SL_BOOLEAN_TRUE};
    result = (*engineEngine)->CreateAudioPlayer(engineEngine,&fdPlayerObject,
         &audioSrc,&audioSNK,3,ids,req);
    assert(SL_RESULT_SUCCESS==result);
    (void)result;

    //realize the player
    result = (*fdPlayerObject)->Realize(fdPlayerObject,SL_BOOLEAN_FALSE);
    assert(SL_RESULT_SUCCESS ==result);
    (void)result;

    //get the play interface
    result=(*fdPlayerObject)->GetInterface(fdPlayerObject,SL_IID_PLAY,
         &fdPlayerPlay);
    assert(SL_RESULT_SUCCESS==result);
    (void)result;


    // get the seek interface
    result = (*fdPlayerObject)->GetInterface(fdPlayerObject, SL_IID_SEEK, &fdPlayerSeek);
    assert(SL_RESULT_SUCCESS == result);
    (void)result;

    // get the mute/solo interface
//    result = (*fdPlayerObject)->GetInterface(fdPlayerObject, SL_IID_MUTESOLO, &fdPlayerMuteSolo);
//    assert(SL_RESULT_SUCCESS == result);
//    (void)result;

    // get the volume interface
    result = (*fdPlayerObject)->GetInterface(fdPlayerObject, SL_IID_VOLUME, &fdPlayerVolume);
    assert(SL_RESULT_SUCCESS == result);
    (void)result;

    //第四步，设置播放状态
    if (NULL != fdPlayerPlay) {

        result = (*fdPlayerPlay)->SetPlayState(fdPlayerPlay, SL_PLAYSTATE_PLAYING);
        (void)result;
    }


    //设置播放音量 （100 * -50：静音 ）
    (*fdPlayerVolume)->SetVolumeLevel(fdPlayerVolume, 20 * -50);


    // enable whole file looping
    result = (*fdPlayerSeek)->SetLoop(fdPlayerSeek, SL_BOOLEAN_TRUE, 0, SL_TIME_UNKNOWN);
    assert(SL_RESULT_SUCCESS == result);
    (void)result;

    return JNI_TRUE;
}

/*
 * Class:     zhaojing_com_myowntest_activity_NativeAudioActivity
 * Method:    setPlayingAssetAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_zhaojing_com_myowntest_activity_NativeAudioActivity_setPlayingAssetAudioPlayer
  (JNIEnv *env, jclass jclazz, jboolean isPlaying){

    SLresult  result;

    //make sure the asset audio player was created
    if(NULL!=fdPlayerPlay){

        //set the player's state
        result=(*fdPlayerPlay)->SetPlayState(fdPlayerPlay,isPlaying ?
            SL_PLAYSTATE_PLAYING:SL_PLAYSTATE_PAUSED);
        assert(SL_RESULT_SUCCESS == result);
        (void)result;
    }
}

/*
 * Class:     zhaojing_com_myowntest_activity_NativeAudioActivity
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zhaojing_com_myowntest_activity_NativeAudioActivity_shutdown
  (JNIEnv *env, jclass jclazz){

    // destroy file descriptor audio player object, and invalidate all associated interfaces
    if (fdPlayerObject != NULL) {
        (*fdPlayerObject)->Destroy(fdPlayerObject);
        fdPlayerObject = NULL;
        fdPlayerPlay = NULL;
        fdPlayerSeek = NULL;
        fdPlayerMuteSolo = NULL;
        fdPlayerVolume = NULL;
    }

    // destroy output mix object, and invalidate all associated interfaces
    if (outputMixObject != NULL) {
        (*outputMixObject)->Destroy(outputMixObject);
        outputMixObject = NULL;
        outputMixEnvironmentalReverb = NULL;
    }
    // destroy engine object, and invalidate all associated interfaces
    if (engineObject != NULL) {
        (*engineObject)->Destroy(engineObject);
        engineObject = NULL;
        engineEngine = NULL;
    }
}

#ifdef __cplusplus
}
#endif
#endif
