/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zhaojing_com_myowntest_ndk_NDKUtils */

#ifndef _Included_zhaojing_com_myowntest_ndk_NDKUtils
#define _Included_zhaojing_com_myowntest_ndk_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zhaojing_com_myowntest_ndk_NDKUtils
 * Method:    getStringFromNative
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zhaojing_com_myowntest_ndk_NDKUtils_getStringFromNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
